---
config:
  theme: neo
---
timeline
    title Timeline of Authentication implementation
    section Client Side
        1.0 Create session : 1.0:submit correct uname / pwd to db : 2.0:either from ui direct user to dashboard : 3.0:or let backend redirect user to dashboard
        2.0 Delete session : 1.0:on logout button click, call delete session api then on successfull response : 2.0:either redirect user from ui : 3.0:or let backend redirect user to signin  
        3.0 Update Session : 1.0:update ui session on every ui action on ui : 2.0:also update backend session
    section Server Side
        1.0 Create Session : 1.0:on correct uname/pwd create session entry in db : 2.0:create cookies by that session ids in index.html : 3.0:route user to dashboard
        2.0 Delete Session : 1.0:once user clicks logout : 2.0:delete session entry from db : 3.0:redirect user to login page
        3.0 Update Session : 1.0:update session on db